### ISSUE TITLE
Practica 9

### ISSUE THREAD

**Issue by 22620229Angel** [SistemasTecTlaxiaco/actividad-9-diagrama-de-clases-secuencia-equipo-osteas-b#1]
[Practica 9 fundamentos.pdf](https://github.com/user-attachments/files/18029865/Practica.9.fundamentos.pdf)

**Comment by ArcangelGC** [comment]
La portada, los indices y el contenido estan de acuerdo a la rubrica.
Tienes ambos diagramas y cumple con lo establecido, muy buen trabajo.
Recomendaciones: Pueden meterle estilo a sus diagramas para que no se vea en un estilo muy simple.

Calif. 30/30

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
